name = "bungibindies"
version = "1.1.8"
description = "Gleam bindings to the Bun runtime API's. PLEASE CONTRIBUTE!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "strawmelonjuice", repo = "bungibindies" }
links = [{ title = "Bun APIs", href = "https://bun.sh/docs/runtime/bun-apis" }]
target = "javascript"
runtime = "bun"
gleam = ">= 1.9.0"

[javascript]
typescript_declarations = true
runtime = "bun"

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.3.0 and < 2.0.0"


[documentation]
pages = [
  { title = "Progress", path = "PROGRESS.html", source = "./PROGRESS.md" },
]
