name = "bungibindies"
version = "1.1.3"
description = "Gleam bindings to the Bun runtime API's."
licences = ["Apache-2.0"]
repository = { type = "github", user = "strawmelonjuice", repo = "bungibindies" }
links = [{ title = "Bun APIs", href = "https://bun.sh/docs/runtime/bun-apis" }]

target = "javascript"
gleam = ">= 1.7.0"

[javascript]
typescript_declarations = true
runtime = "bun"

[dependencies]
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_stdlib = ">= 0.0.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"


[documentation]
pages = [
  { title = "Progress", path = "PROGRESS.html", source = "./PROGRESS.md" },
]
