name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bunx "@biomejs/biome" check --write
          git restore --source=HEAD --staged --worktree -- ./.github
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Biome fixes"
