name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: "1.7.0"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
